import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.function.Function;
import java.util.stream.Collectors;

public class  MapAutoGeneratedId{

   // static int j=0;
     
    public static void main(String[] args) {
        var ref = new Object() {
            int j = -1;
        };
        List<String> list =  Arrays.asList("Vishwa","Ram","Mohan","Sohan");
        Map<Integer,String> map = list.stream().collect(Collectors.toMap(s->{return ref.j = ref.j +1;}, Function.identity()));
        System.out.println(map);
        map.forEach((k,v)-> {
            System.out.print(k+"  ");
            System.out.println(v);
        });

    }
}
